# Generated by Django 4.2.17 on 2025-03-27 04:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reportmanager", "0008_bucket_reassign_in_progress"),
    ]

    operations = [
        migrations.AddField(
            model_name="reportentry",
            name="comments_original_language",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="reportentry",
            name="comments_translated",
            field=models.TextField(null=True),
        ),
    ]
