# Generated by Django 4.2.17 on 2025-07-09 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportmanager', '0009_reportentry_comments_original_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportentry',
            name='ml_valid_probability',
            field=models.FloatField(null=True),
        ),
    ]
